[skip ci] try fixing trigger job conditions and docker run command

diff --git a/.github/workflows/trigger.yml b/.github/workflows/trigger.yml
--- a/.github/workflows/trigger.yml
+++ b/.github/workflows/trigger.yml
@@ -20,7 +20,7 @@ jobs:
       run: node generator bitmeal/nodegit --node-versions 3 --nodegit-versions 3 > manifest-check.json
     - name: Test for new Node or Nodegit versions
       id: check-versions
-      run: diff -q manifest.json manifest-check.json && (echo "No updates"; echo "::set-output name=diff::false") || (echo "New versions detected; check container versions."; echo "::set-output name=diff::true")
+      run: diff -q manifest.json manifest-check.json && (echo "No updates") || (echo "New versions detected; check container versions."; echo "::set-output name=diff::true")
 
   check-versions:
     runs-on: ubuntu-latest
@@ -40,7 +40,7 @@ jobs:
       run: node generator bitmeal/nodegit --node-versions 3 --nodegit-versions 3 > manifest-check.json
     - name: Test node:alpine container versions against expected node versions
       id: check-containers
-      run: (for version in $(cat manifest-check.json | jq -r '."version-info".node[]'); do [ "$(docker run --rm node:$(echo ${version} | grep -E -o '^\d+')-alpine node --version)" == "v${version}" ] && echo "${version} [OK]" || (echo "${version} [FAILED]"; false); done) && (echo "Container node versions match [OK]"; echo "::set-output name=match::true") || (echo "Container node versions DON'T match [FAILED]"; echo "::set-output name=match::false")
+      run: (for version in $(cat manifest-check.json | jq -r '."version-info".node[]'); do [ "$(docker run --rm node:$(echo ${version} | grep -oP '^\d+')-alpine node --version)" == "v${version}" ] && echo "${version} [OK]" || (echo "${version} [FAILED]"; false); done) && (echo "Container node versions match [OK]"; echo "::set-output name=match::true") || (echo "Container node versions DON'T match [FAILED]")
     - uses: actions/upload-artifact@v2
       with:
         name: manifest.json
